=== dbertini/TheRetriever/schemas/ReportSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="report" nillable="false">
		<xs:complexType>
			<xs:all>
				<xs:element name="name" type="xs:string" minOccurs="1"></xs:element>
				<xs:element name="datasource" type="xs:string" minOccurs="1"></xs:element>
				<xs:element name="sql" type="xs:string" minOccurs="1"></xs:element>
				<xs:element name="cron" type="xs:string" minOccurs="1"></xs:element>
				<xs:element name="description" type="xs:string" minOccurs="1"></xs:element>
				<xs:element name="recipient" type="xs:string" minOccurs="1"></xs:element>
				<xs:element name="cclist" type="xs:string" minOccurs="0"></xs:element>
				<xs:element name="ccnlist" type="xs:string" minOccurs="0"></xs:element>
				<xs:element name="export" type="exportType" minOccurs="1"></xs:element>
				<xs:element name="template" type="xs:string" minOccurs="0"></xs:element>
				<xs:element name="filename" type="xs:string" minOccurs="0"></xs:element>
				<xs:element name="executionId" type="xs:string" minOccurs="0"></xs:element>
				<xs:element name="lastStartTime" type="xs:string" minOccurs="0"></xs:element>
				<xs:element name="lastStopTime" type="xs:string" minOccurs="0"></xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="exportType">
		<xs:restriction>
				<xs:simpleType>
					<xs:list>
						<xs:simpleType>
							<xs:restriction base="xs:token">
								<xs:enumeration value="CSV" />
								<xs:enumeration value="XML" />
								<xs:enumeration value="CSVEXCEL" />
								<xs:enumeration value="EXCEL" />
							</xs:restriction>
						</xs:simpleType>
					</xs:list>
				</xs:simpleType>
			</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== dbertini/TheRetriever/reports/report.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE report>
<report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ReportSchema.xsd">
	<name>report1</name>
	<datasource>postgres</datasource>
	<sql>
		select now()
	</sql>
	<cron>00 31 12 ? * MON,TUE,WED,THU,FRI</cron>
	<description>Report estrazione data</description>
	<recipient>david.bertini@gmail.com</recipient>
	<cclist>david.bertini@gmail.com</cclist>
	<ccnlist>david.bertini@gmail.com</ccnlist>
	<export>EXCEL</export>
	<template>template_001</template>
</report>

=== dbertini/TheRetriever/reports/report2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE report>
<report xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ReportSchema.xsd">
	<name>report2</name>
	<datasource>monet</datasource>
	<sql>
		select *
          from wsuser.cerved_mon_nonclienti a,
               movimenti_posizioni x
 		 where a.id_anagrafica = x.ndg
   		   and a.abi = x.abi
	</sql>
	<cron>00 00 10 ? * MON,TUE,WED,THU,FRI</cron>
	<description>Report estrazione data</description>
	<recipient>david.bertini@gmail.com</recipient>
<!-- 	<cclist>david.bertini@gmail.com</cclist> -->
<!-- 	<ccnlist>david.bertini@gmail.com</ccnlist> -->
	<export>EXCEL</export>
<!-- 	<template>template_001</template> -->
</report>
