=== dbertini/TheRetriever/schemas/TemplateSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<xs:element name="template">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name" minOccurs="1" />
				<xs:element ref="title" minOccurs="0" />
				<xs:element ref="titleTextColor" minOccurs="0" />
				<xs:element ref="titleBkgColor" minOccurs="0" />
				<xs:element ref="headers" minOccurs="0" />
				<xs:element ref="coloumns" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="title" type="xs:string" />
	<xs:element name="titleTextColor" type="xs:string" />
	<xs:element name="titleBkgColor" type="xs:string" />
	<xs:element name="headers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="textColor" minOccurs="0" />
				<xs:element ref="bkgColor" minOccurs="0" />
				<xs:element ref="valign" minOccurs="0" />
				<xs:element ref="halign" minOccurs="0" />
				<xs:element ref="boxed" minOccurs="0" />
				<xs:element ref="headersDefinition" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="headersDefinition" nillable="true">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="headerDefinition" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="headerDefinition" nillable="true">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name" minOccurs="1" />
				<xs:element ref="heading" minOccurs="1" />
				<xs:element ref="textColor" minOccurs="0" />
				<xs:element ref="bkgColor" minOccurs="0" />
				<xs:element ref="valign" minOccurs="0" />
				<xs:element ref="halign" minOccurs="0" />
				<xs:element ref="boxed" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="heading" type="xs:string" />
	<xs:element name="coloumns">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" ref="coloumn" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="coloumn">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name" minOccurs="1" />
				<xs:element ref="textColor" minOccurs="0" />
				<xs:element ref="bkgColor" minOccurs="0" />
				<xs:element ref="format" minOccurs="0" />
				<xs:element ref="valign" minOccurs="0" />
				<xs:element ref="halign" minOccurs="0" />
				<xs:element ref="boxed" minOccurs="0" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="format" type="xs:string" />
	<xs:element name="name" type="xs:NCName" />
	<xs:element name="textColor" type="xs:string" />
	<xs:element name="bkgColor" type="xs:string" />
	<xs:element name="valign" type="valignType" />
	<xs:element name="halign" type="halignType" />
	<xs:element name="boxed" type="boxedType" />

	<xs:simpleType name="valignType">
		<xs:restriction>
			<xs:simpleType>
				<xs:list>
					<xs:simpleType>
						<xs:restriction base="xs:token">
							<xs:enumeration value="TOP" />
							<xs:enumeration value="CENTER" />
							<xs:enumeration value="BOTTOM" />
							<xs:enumeration value="JUSTIFY" />
							<xs:enumeration value="DISTRIBUTED" />
						</xs:restriction>
					</xs:simpleType>
				</xs:list>
			</xs:simpleType>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="halignType">
		<xs:restriction>
			<xs:simpleType>
				<xs:list>
					<xs:simpleType>
						<xs:restriction base="xs:token">
							<xs:enumeration value="GENERAL" />
							<xs:enumeration value="LEFT" />
							<xs:enumeration value="CENTER" />
							<xs:enumeration value="RIGHT" />
							<xs:enumeration value="FILL" />
							<xs:enumeration value="JUSTIFY" />
							<xs:enumeration value="CENTER_SELECTION" />
							<xs:enumeration value="DISTRIBUTED" />
						</xs:restriction>
					</xs:simpleType>
				</xs:list>
			</xs:simpleType>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="boxedType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute ref="border" use="optional"/>
        <xs:attribute name="color" type="xs:string" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
	
	<xs:attribute name="border">
		<xs:simpleType>
			<xs:restriction>
				<xs:simpleType>
					<xs:list>
						<xs:simpleType>
							<xs:restriction base="xs:token">
								<xs:enumeration value="NONE" />
								<xs:enumeration value="THIN" />
								<xs:enumeration value="MEDIUM" />
								<xs:enumeration value="DASHED" />
								<xs:enumeration value="DOTTED" />
								<xs:enumeration value="THICK" />
								<xs:enumeration value="DOUBLE" />
								<xs:enumeration value="HAIR" />
								<xs:enumeration value="MEDIUM_DASHED" />
								<xs:enumeration value="DASH_DOT" />
								<xs:enumeration value="MEDIUM_DASH_DOT" />
								<xs:enumeration value="DASH_DOT_DOT" />
								<xs:enumeration value="MEDIUM_DASH_DOT_DOT" />
								<xs:enumeration value="SLANTED_DASH_DOT" />
							</xs:restriction>
						</xs:simpleType>
					</xs:list>
				</xs:simpleType>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>

</xs:schema>

=== dbertini/TheRetriever/templates/template_base.xml
<?xml version="1.0" encoding="UTF-8"?>
<template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/TemplateSchema.xsd">
	<name>template_base</name>
<!-- 	<title>Titolo del template</title> -->
<!-- 	<titleTextColor>0,0,0</titleTextColor> -->
<!-- 	<titleBkgColor>155,155,155</titleBkgColor> -->
	<headers>
		<textColor>255,255,255</textColor>
		<bkgColor>150,150,150</bkgColor>
		<valign>CENTER</valign>
		<halign>CENTER</halign>
		<boxed border="MEDIUM" color="0,0,0">Y</boxed>
		<headersDefinition>
			<headerDefinition>
				<name>CONTO</name>
				<heading>Numero Variazioni</heading>
<!-- 				<textColor>200,200,200</textColor> -->
<!-- 				<bkgColor>10,10,10</bkgColor> -->
<!-- 				<valign>CENTER</valign> -->
<!-- 				<halign>LEFT</halign> -->
<!-- 				<boxed border="SLANTED_DASH_DOT" color="255,125,0">Y</boxed> -->
			</headerDefinition>
			<headerDefinition>
				<name>COD_ISTITUTO</name>
				<heading>Cod. Istituto</heading>
<!-- 				<textColor>200,200,200</textColor> -->
<!-- 				<bkgColor>10,10,10</bkgColor> -->
<!-- 				<boxed border="MEDIUM_DASHED" color="0,0,0">N</boxed> -->
			</headerDefinition>
			<headerDefinition>
				<name>ABI</name>
				<heading>ABI</heading>
<!-- 				<textColor>200,200,200</textColor> -->
<!-- 				<bkgColor>10,10,10</bkgColor> -->
<!-- 				<valign>CENTER</valign> -->
<!-- 				<halign>LEFT</halign> -->
<!-- 				<boxed border="MEDIUM_DASHED" color="0,0,0">Y</boxed> -->
			</headerDefinition>
			<headerDefinition>
				<name>BANCA</name>
				<heading>Descrizione Bcc</heading>
<!-- 				<textColor>200,200,200</textColor> -->
<!-- 				<bkgColor>10,10,10</bkgColor> -->
<!-- 				<valign>CENTER</valign> -->
<!-- 				<halign>LEFT</halign> -->
<!-- 				<boxed border="MEDIUM_DASHED" color="0,0,0">Y</boxed> -->
			</headerDefinition>
		</headersDefinition>
	</headers>
	<coloumns>
		<coloumn>
			<name>CONTO</name>
			<valign>CENTER</valign>
			<halign>CENTER</halign>
			<boxed border="MEDIUM" color="0,0,0">Y</boxed>
		</coloumn>
		<coloumn>
			<name>COD_ISTITUTO</name>
			<valign>CENTER</valign>
			<halign>CENTER</halign>
			<boxed border="MEDIUM" color="0,0,0">Y</boxed>
		</coloumn>
		<coloumn>
			<name>ABI</name>
			<valign>CENTER</valign>
			<halign>CENTER</halign>
			<boxed border="MEDIUM" color="0,0,0">Y</boxed>
		</coloumn>
		<coloumn>
			<name>BANCA</name>
			<valign>CENTER</valign>
			<halign>CENTER</halign>
			<boxed border="MEDIUM" color="0,0,0">Y</boxed>
		</coloumn>
	</coloumns>
</template>

=== dbertini/TheRetriever/templates/template.xml
<?xml version="1.0" encoding="UTF-8"?>
<template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/TemplateSchema.xsd">
	<name>template_001</name>
	<title>Titolo del template</title>
	<titleTextColor>0,0,0</titleTextColor>
	<titleBkgColor>155,155,155</titleBkgColor>
	<headers>
		<textColor>255,0,255</textColor>
		<bkgColor>200,200,200</bkgColor>
		<valign>BOTTOM</valign>
		<halign>RIGHT</halign>
		<boxed border="MEDIUM" color="255,255,0">Y</boxed>
		<headersDefinition>
			<headerDefinition>
				<name>ID_MOVIMENTO</name>
				<heading>Colonna 1</heading>
				<textColor>200,200,200</textColor>
				<bkgColor>10,10,10</bkgColor>
				<valign>CENTER</valign>
				<halign>LEFT</halign>
				<boxed border="SLANTED_DASH_DOT" color="255,125,0">Y</boxed>
			</headerDefinition>
			<headerDefinition>
				<name>ABI</name>
				<heading>Colonna 2</heading>
				<textColor>200,200,200</textColor>
				<bkgColor>10,10,10</bkgColor>
				<boxed border="MEDIUM_DASHED" color="0,0,0">N</boxed>
			</headerDefinition>
			<headerDefinition>
				<name>DATA_INSERIMENTO</name>
				<heading>Data Inserimento</heading>
				<textColor>200,200,200</textColor>
				<bkgColor>10,10,10</bkgColor>
				<valign>CENTER</valign>
				<halign>LEFT</halign>
				<boxed border="MEDIUM_DASHED" color="0,0,0">Y</boxed>
			</headerDefinition>
		</headersDefinition>
	</headers>
	<coloumns>
		<coloumn>
			<name>ID_MOVIMENTO</name>
			<textColor>200,200,200</textColor>
			<bkgColor>47,200,125</bkgColor>
			<format>###########</format>
			<valign>CENTER</valign>
			<halign>RIGHT</halign>
			<boxed border="MEDIUM" color="255,255,0">Y</boxed>
		</coloumn>
		<coloumn>
			<name>ABI</name>
			<textColor>200,200,200</textColor>
			<bkgColor>125,10,234</bkgColor>
			<format></format>
			<valign>CENTER</valign>
			<halign>LEFT</halign>
			<boxed>N</boxed>
		</coloumn>
		<coloumn>
			<name>DATA_INSERIMENTO</name>
			<textColor>200,200,200</textColor>
			<bkgColor>125,10,234</bkgColor>
			<format>dd/MM/yyyy hh:mm:ss</format>
			<valign>BOTTOM</valign>
			<halign>CENTER</halign>
			<boxed border="MEDIUM_DASH_DOT" color="255,69,0">Y</boxed>
		</coloumn>
	</coloumns>
</template>
